### ISSUE TITLE
inheritance test not clear about "surlined" message

### ISSUE THREAD

**Issue by stonebig** [PierreRaybaut/guidata#27]
Maybe it's my screen or my brain: I don't see where is that "surligné" field

![guidata_inheritance_cryptic_message](https://cloud.githubusercontent.com/assets/4312421/11016202/dbc4eb74-8579-11e5-8ca6-eab6bdea25a6.GIF)

**Comment by PierreRaybaut** [comment]
The 3 last fields ("Level 1", "Level 2a" and "Level 2b") are highlighted because floats are expected instead of strings (see tooltip when hovering those fields with the mouse cursor).

**Comment by stonebig** [comment]
ah, ok.
