### ISSUE TITLE
Application icon isn't set properly

### ISSUE THREAD

**Issue by diegorubert** [PierreRaybaut/guidata#37]
At editgroupbox.py example, the application icon at taskbar isn't set properly. I couldn't find what is wrong. I'm using the latest version with Python 2.7.11+ and python-qt4 4.11.4+dfsg-1+b3, Debian Sid.

![error](https://cloud.githubusercontent.com/assets/19498369/15444510/95683fb6-1ebf-11e6-8a58-19851e4e710c.jpg)

**Comment by PierreRaybaut** [comment]
The application icon is set by Qt: the fact that it's not set correctly is a known Qt bug for some old versions.
There is a workaround somewhere ; I may look around and find it if you're still interested.
