### ISSUE TITLE
Guidata can not be installed on python 2.6

### ISSUE THREAD

**Issue by msmk0** [PierreRaybaut/guidata#42]
When trying to install guidata via `pip install --user guidata` with python 2.6, the installation breaks with the following error message:

    File "/tmp/caribou/pip-build-6m1nnH/guidata/setup.py", line 151, in <module>
        % sys.version_info.major,]},
    AttributeError: 'tuple' object has no attribute 'major'

The `setup.py` script uses the named accessor `sys.version_info.major` which is only accessible from python 2.7 onwards. However, the meta-data lists compatibility with python 2.6.

**Comment by PierreRaybaut** [comment]
Python 2.6 is no longer supported
