### ISSUE TITLE
Link to documentation does not work

### ISSUE THREAD

**Issue by mfhepp** [PierreRaybaut/guidata#48]
The link to "documentation" in the [README.md](https://github.com/PierreRaybaut/guidata/blob/master/README.md) points to 

https://pythonhosted.org/guidata/

which returns a 404 error:

```
$ curl -I https://pythonhosted.org/guidata/
HTTP/1.1 404 Not Found
```

Same for the link to the image:

`<img src="http://pythonhosted.org/guidata/_images/editgroupbox.png">
`

**Comment by PierreRaybaut** [comment]
Doc links fixed by 4799bbfc2f0dfe1ccfa4fc0b104f44e91eb608d3
