### ISSUE TITLE
can't build wheel from guidata in winpython 3.4

### ISSUE THREAD

**Issue by stonebig** [PierreRaybaut/guidata#5]
same problem as https://github.com/spyder-ide/spyder/issues/2574

Googling it doesn't enlight me very much.

having guidata provided also as a wheel on pypi would hide the problem.

**Comment by PierreRaybaut** [comment]
I have no clue regarding the "colorama" bug.
But FYI, there is already a wheel package for guidata on PyPI.

**Comment by stonebig** [comment]
ok, thank you, closing
