### ISSUE TITLE
supporting Python-3.10 ?

### ISSUE THREAD

**Issue by stonebig** [PierreRaybaut/guidata#50]
trying guidata-1.8 on python-3.10/pyside6-6.2, I get this error
![image](https://user-images.githubusercontent.com/4312421/137585631-555a59e6-4972-4c1a-b127-9fcae5f59805.png)

I'm not sure how it shall be fixed. 
I saw this https://github.com/hylang/hy/pull/2115/files

**Comment by stonebig** [comment]
it works by replacing collections.Callable per collections.abc.Callable.

  C:\python-3.10.0.amd64\Lib\site-packages\guidata\dataset\dataitems.py (2 hits)
	Line 537:         if isinstance(choices, collections.abc.Callable):  # stonebig
	Line 543:         if default is FirstChoice and not isinstance(choices, collections.abc.Callable): # stonebig


![image](https://user-images.githubusercontent.com/4312421/137585792-184706ee-0343-4f80-bd9d-641c24543cc6.png)

**Comment by PierreRaybaut** [comment]
Fixed by dd3d7ff8f5db7a535fa588b4bb0a80b6d0105128

**Comment by stonebig** [comment]
Thanks, guidata-2.0.2 works way better now on Pyside6/Python-3.10. only test_dataframeeditor.py seems not happy, will have to digg.

![image](https://user-images.githubusercontent.com/4312421/147555920-bd143f85-4e94-401d-96c6-6cd0488b596d.png)

**Comment by PierreRaybaut** [comment]
Fixed by 5cb6ebbb3c40301233d48df5cb663164190419bc
