### ISSUE TITLE
guidata conda-forge package currently broken 

### ISSUE THREAD

**Issue by cpascual** [PierreRaybaut/guidata#54]
Installation of guidata from conda-forge is broken since qtpy was upgraded to v2.0.0 in conda-forge.

This is related to #52.

I am "cross-posting" here after reporting in https://github.com/conda-forge/guidata-feedstock/issues/11 because I am not sure if anyone is monitoring the issues there.

**Comment by cpascual** [comment]
*bump* ;-)

**Comment by PierreRaybaut** [comment]
I suppose this has been solved with recent versions of guidata.

**Comment by cpascual** [comment]
I am afraid that the problem is fixed in guidata>2 (it was already when I created the issue) but it is **not** in the latest conda-forge guidata package, which is still 1.7.9 and has a now-broken dependency (please see https://github.com/conda-forge/guidata-feedstock/issues/11).

I fully agree with closing this issue **here** but something should be done regarding the conda-forge package since that is the main entry-point for many users of guidata and it is currently unusable.
